---
title: "STAT 420 Final Project Proposal"
date: "July 17, 2019"
output:
  html_document: 
    toc: yes
  pdf_document: default
urlcolor: cyan
---

# Group Members
- Tao Li (taol4@illinois.edu)
- Wanlin Yang (wanliny2@illinois.edu)
- Chun yue Shek (cyshek2@illinois.edu)

# Problem

How does Weight, Clarity, Color and Cut influence diamond's price?

# Dataset

We will use the [Diamonds](https://www.kaggle.com/shivam2503/diamonds) dataset for our final project.

## Description
This classic dataset contains the prices and other attributes of almost 54,000 diamonds. It's a great dataset for us to work with data analysis and visualization.

There are totally 53940 rows and 10 variables in the dataset.

- **price**: price in US dollars (\$326--\$18,823)
- **carat**: weight of the diamond (0.2--5.01)
- **cut**: quality of the cut (Fair, Good, Very Good, Premium, Ideal)
- **color**: diamond colour, from J (worst) to D (best)
- **clarity**: a measurement of how clear the diamond is (I1 (worst), SI2, SI1, VS2, VS1, VVS2, VVS1, IF (best))
- **x**: length in mm (0--10.74)
- **y**: width in mm (0--58.9)
- **z**: depth in mm (0--31.8)
- **depth**: total depth percentage = z / mean(x, y) = 2 * z / (x + y) (43--79)
- **table**: width of top of diamond relative to widest point (43--95)

## Load into R

There is a csv file in the above link to the dataset, and we can load it into our R program. 

```{r message=FALSE, warning=FALSE}
library(readr)
diamonds = read_csv("diamonds.csv")
diamonds$cut = as.factor(diamonds$cut)
diamonds$color = as.factor(diamonds$color)
diamonds$clarity = as.factor(diamonds$clarity)
```


# Potenrial features to explore

We can use **price** as the response, and the rest as predictors.

By exporing different combination of predictors, transformations, and even transform of response, we can find a relatively best model to predict the price of a dimond. And we will split the dataset into training and test set to do cross-validation.

## 

